### ISSUE TITLE
paratii.core.vids.get(id) doesn't properly work

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-lib#77] opened 2018-01-22 11:50 UTC
I'm calling it like this, in `paratii-portal`
```
let videoInfo = await paratii.core.vids.get(id)
```

but i get this error in browser console

```
index.js?0bef:94 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at BlockService.get (index.js?0bef:94)
    at waterfall (index.js?dddc:364)
    at nextTask (waterfall.js?f8db:16)
    at exports.default (waterfall.js?f8db:26)
    at IPLDResolver._get (index.js?dddc:363)
    at IPLDResolver.get (index.js?dddc:129)
    at Function.get.promisify (object.js?7690:196)
    at eval (index.js?dae6:41)
    at new Promise (<anonymous>)
    at Object.eval [as get] (index.js?dae6:35)
    at ParatiiIPFS.getJSON (paratii.ipfs.js?3bd6:162)
    at <anonymous>
```

**Comment by jellegerbrandy** [comment] 2018-01-22 15:09
I cannot reproduce this.
* start the portal with the latest dev version
* open crhome, go to http://localhost:8080/
* open devtools
* paste `p = paratii.core.vids.get('foo')`
* pase `p`
* check output. Looks ok.

**Comment by jellegerbrandy** [comment] 2018-02-05 08:01
@eliawk , do you still have this bug? Can we close this issue otherwise?

**Closed** 2018-03-26 10:25 UTC
