### ISSUE TITLE
Clear up mechanism for CRUD operations on videos

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-lib#24] opened 2017-12-26 19:43 UTC
**Problem**
Currently, the only (I think) way to use `paratii-lib` to get data about a video (given the video ID) is to use `ParatiiEth`. To instantiate `ParatiiEth`, you need an ethereum address (along w/ some other config). However, I think you should be able to retrieve info about a video w/o having any particular user's eth address. 

@jellegerbrandy does this make sense? If yes, we can figure out how to expose this api (and potentially others that should not require an address). If not, please inform me of the appropriate way to fetch this data/use the lib 😄 

cc @ya7ya

**Comment by jellegerbrandy** [comment] 2017-12-27 10:42
Yeah, sorry about the lack of documentation, I'll try to update it. Work in progress. Also there are many things that are simply not working yet. Here's some pointers:

- Need ethereum address for fetching data of video:  if it's true, it is  a bug.
- There should be no need in the client code to instantiate ParatiiEth directly. The way to use it would be to have one single `paratii = new Paratii(..)` instance in the app, and access the paratiiEth instance as the `eth` attribute on  your object, i.e. as `paratii.eth` 
-  The situation is complex, and the API and docs should hide this complexitity but does not do so very well yet. But the pattern for getting information about a video once you have the videoId would be:

     let paratii = new Paratii({provider: ...})
     paratii.core.videos.get(videoId)

Actually, I am thinking of removing this `core` invocation as well, so it can just become: `paratii.videos.get()`. 

- To give you an idea of the inner workings:
     `paratii.eth.videos.get(videoId)` : query the blockcahin for information about the video. (this info is partial, because some info is stored in ipfs)
     `paratii.db.videos.get(videoId)` (**not working yet**): get video info from the database index, a service that we provide, that makes the info we have stored about videos on the blockahin and in ipfs indexed and searchable
     `paratii.core.videos.get(videoId)`: get info about hte video, you don't care where it comes from. At the moment, this will get data from blockahin and ipfs, in a next iteration it should just call `paratii.db.videos.get`.

**Comment by bent0b0x** [comment] 2017-12-27 13:28
I will change the title of this issue because I think you do not, in fact, need an eth address to fetch data about a video. However, I cannot get it working still.

Right now I am using code like this:

```javascript
const paratii = new Paratii({
  provider: "http://localhost:8545"
});

paratii.core.vids
  .create({
    id: "0x90f8bf6a479",
    owner: "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1"
  })
  .then(() => {
    paratii.core.vids
      .get("0x90f8bf6a479")
      .then(res => {
        console.log(res);
      })
      .catch(e => {
        console.log("e: ", e);
      });
  });
```

which results in an error:
![image](https://user-images.githubusercontent.com/7697924/34382896-b335a9b4-eadf-11e7-9628-aed27dd71a84.png)

Also to note, if I try to include a property of `ipfsHash` in the `create()` call, I get this error:

![image](https://user-images.githubusercontent.com/7697924/34382929-d8581a06-eadf-11e7-9666-0299af240266.png)

**Comment by ya7ya** [comment] 2017-12-27 13:30
hey @bent0b0x , this is pretty weird since this code has nothing to do with ipfs 😏 . I'll investigate deeper. Thanks for the heads up.

**Comment by jellegerbrandy** [comment] 2017-12-27 13:44
@bent0b0x: ok, probably a bug. The fact that you cannot pass ain ipfsHash explicitly is correct. Can you push a branch with this bug, so we save time on trying to reproduce?

@ya7ya : The calls from `core` may touch on the ipfs code - the idea is that `parati.eth` does the blockcahin stuff,  `paratii.ipfs` the ipfs things, `paratii.db` the database stuff, and `paratii.core` (which is what ben is using here) ties everything together and can (and does) call ipfs under the hood.

**Comment by ya7ya** [comment] 2017-12-27 13:50
@bent0b0x @jellegerbrandy I figured out the problem, the `this.config` in `getIPFSInstance` changes based on the scope of the function that calls it. so `Cannot read property 'closed' of null` is because the repo was null. i'm gonna push the fixes now to the `ipfs` branch

**Comment by jellegerbrandy** [comment] 2017-12-27 13:51
In any case, @bent0b0x , here is the corresponding test (which works and seems verys imilar to your code) for reference: https://github.com/Paratii-Video/paratii-lib/blob/master/test/paratii.core.vids.js#L19

**Comment by ya7ya** [comment] 2017-12-27 13:53
Error fixed in this commit https://github.com/Paratii-Video/paratii-lib/commit/f84578d0b92a97d48b1df3edc6108c1e4a677903 

@bent0b0x Let me know if you're still having issues with this.

**Comment by bent0b0x** [comment] 2017-12-27 14:07
Thanks @ya7ya, that cleared up that issue! However, now I see this:

![image](https://user-images.githubusercontent.com/7697924/34383733-690a7da0-eae5-11e7-90fe-78ae54c846ca.png)

**Comment by ya7ya** [comment] 2017-12-27 14:08
@bent0b0x oh, i see, I'll push a fix now 👍

**Comment by bent0b0x** [comment] 2017-12-27 14:09
If you check out the branch `16-player` you can test this out, load up `localhost:8080` and the app will try to run the lib code (via `VideoActions.js`)

**Comment by ya7ya** [comment] 2017-12-27 14:13
@bent0b0x fixed in https://github.com/Paratii-Video/paratii-lib/commit/7778f678bd95e42a669da32046f1fb3799e3f1ff 

Let me know if something else pops up 😄 👍

**Comment by bent0b0x** [comment] 2017-12-27 14:21
![image](https://user-images.githubusercontent.com/7697924/34383989-353c7508-eae7-11e7-9131-8f73c7992dbd.png)

It looks like calling paratii core indirectly calls paratii eth, which leads to problem given how I'm instantiating `Paratii`. Thoughts?

**Comment by ya7ya** [comment] 2017-12-27 14:25
cc @jellegerbrandy ☝️ 

@bent0b0x you sure `testrpc` is up and running ? we probably need to deploy a test registry i think

**Comment by bent0b0x** [comment] 2017-12-27 14:28
Yes it is running

**Comment by bent0b0x** [comment] 2017-12-27 17:57
@jellegerbrandy I tried your suggestion of calling `paratii.eth.deployContracts()`, but I get the following error:

![image](https://user-images.githubusercontent.com/7697924/34389077-806e01a4-eb05-11e7-941e-5e4ef64cdbbd.png)

**Comment by jellegerbrandy** [comment] 2017-12-28 09:07
Yes. 
So you need an ethereofum account to write stuff to the blockchain (such as deploying contracts).  That means you need to provide an `address` as well as a way of signing messages with that address (either a private key or a wallet loaded from localStorage):

This can be either specified on start up
  
       Paratii({ address: 0x12345, privateKey: 'xxxx })



Or with the `setAccount` function indicated in the error message:

       paratii.setAccount({ address: '0x2332', privateKey: 'dsfaskfd'})

Where to get that key? It needs to be of an account that has some ether available to pay for the transactions. We are now setting  this up https://github.com/Paratii-Video/paratii-lib/issues/31, should be done today, and then we use the same config for testig in the portal.

**Comment by bent0b0x** [comment] 2017-12-29 20:57
@jellegerbrandy the private key for this test account, is this something we don't mind publishing in our code? 

I'm still unclear on what we are doing for production. What does this address represent? Is it paratii's address so that we can communicate w/ the blockchain for the user?

**Comment by bent0b0x** [comment] 2017-12-29 21:47
Okay, I think I am very close to having this working (at least for a POC) in the portal. I am able to instantiate `paratii-lib`, deploy the contracts, and then create a video like so:

```
lib.core.vids
      .create({
        id,
        price: 0,
        owner: '0xa99dBd162ad5E1601E8d8B20703e5A3bA5c00Be7'
      })
```

Then I can fetch it with a `.get()`.

Now, I would like to test actually `.get()`-ing a video that is streamable via ipfs (because in the example above I am creating a dummy video). My first thought was to take the `ipfsHash` from a video that we are already using in paratii player and add that in to my `.create()` call, but I get errors saying that `ipfsHash` is not an allowed property. 

Anyways, I feel like I might be going down the wrong route anyway. Thoughts on how to do this?

**Comment by jellegerbrandy** [comment] 2017-12-30 10:02
This is exactly the way it is supposed to be used.

The core.vids.create() does not take the ipfsHash, because I thought that the typical case would be that it would take a 'file' argument and create the hash itself. I created an issue on the paratii-lib repo to add this: https://github.com/Paratii-Video/paratii-lib/issues/39

**Comment by bent0b0x** [comment] 2017-12-31 02:20
@jellegerbrandy I think passing in `file` does, indeed, make the most sense. I was trying to pass in `ipfsHash` for testing purposes. Is the `file` prop supported right now? I'll give it a try, I'm not sure that #39 will be necessary

**Comment by jellegerbrandy** [comment] 2018-01-02 09:04
here some more responses to your questions, @bent0b0x 

- The address (and private key) used when initializating Paratii represent the *users*'s ethereum address
- Each client instance always has an associated ethereum address. Even when we do what we called "anonymous navigation" -  if we do not know which user we have (i.e. there is no cookie), we simply generate a new address. 
-  We don't mind publishing the test private key, because it is an account used for testing purposes only. It is just "some" account.
-  About the ipfshash arg: I think it is still useful in any case to be able to set the hash directory. (Typically, this will be the hash of the transcoded files - i.e. it may take a long time to go from `file` to `ipfshash`, because we need to do all the transcoding). So I'll leave #39 open. 
-  The "file" argument should probably be of type "filestream". https://github.com/Paratii-Video/paratii-lib/issues/44
- And it is not yet working (core.vids.create() ignored the file argument: https://github.com/Paratii-Video/paratii-lib/issues/46)

**Comment by bent0b0x** [comment] 2018-01-03 22:41
Thanks! I've added my questions below in bold:

- The address (and private key) used when initializating Paratii represent the *users*'s ethereum address 
- Each client instance always has an associated ethereum address. Even when we do what we called "anonymous navigation" -  if we do not know which user we have (i.e. there is no cookie), we simply generate a new address. **what part of our stack is taking care of this? Will we have to replicate this functionality (that I'm assuming existed) in `paratii-video` and port it to `paratii-portal`? And then store this data in `paratii-portal`'s application state?**
-  We don't mind publishing the test private key, because it is an account used for testing purposes only. It is just "some" account. **If our tests are reliant on this test account having some amount of ETH/PTI, is there an api in `paratii-lib` to set the amount of ETH/PTI associated w/ an account? Otherwise we will end up coding tests w/o knowing the exact balance of our account**
-  About the ipfshash arg: I think it is still useful in any case to be able to set the hash directory. (Typically, this will be the hash of the transcoded files - i.e. it may take a long time to go from `file` to `ipfshash`, because we need to do all the transcoding). So I'll leave #39 open. 
-  The "file" argument should probably be of type "filestream". https://github.com/Paratii-Video/paratii-lib/issues/44
- And it is not yet working (core.vids.create() ignored the file argument: https://github.com/Paratii-Video/paratii-lib/issues/46)

**Comment by jellegerbrandy** [comment] 2018-01-04 13:22
Regarding your first question: who/what is taking care of each client already having an ethereum address.  So, yes, in `paratii-player` it was already working like that, the tests are here: https://github.com/Paratii-Video/paratii-portal/blob/dev/test/functional-tests/profile.spec.js

In paratii-lib, this stuff is handled by various functions in `paratii.eth.wallet` that are used for createing and serializing account info; the `paratii-portal` code will have to glue this together and call the right things at the right moment: how that should be done is encoded in the  `profile.spec.js`. (more or less, that is)

Regarding the question: how is the test account gonna get some PTI and ETH to work with? I think we can use the same mechanism as in `paratii-lib` (where we are also setting up a test account and giving it some money). @geckoslair  coded that, I have not looked into the details.

**Comment by jellegerbrandy** [comment] 2018-02-05 08:20
closing this as I do not see anything actionable anymore... feel free to reopen of create a new issues if things were left unresolved

**Closed by jellegerbrandy** 2018-02-05 08:20 UTC
